package com.xzx.crawler.dao;

import com.xzx.crawler.entity.Article;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Fri Jan 08 20:11:51 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Fri Jan 08 20:11:51 CST 2021
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Fri Jan 08 20:11:51 CST 2021
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Fri Jan 08 20:11:51 CST 2021
     */
    Article selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Fri Jan 08 20:11:51 CST 2021
     */
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Fri Jan 08 20:11:51 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Fri Jan 08 20:11:51 CST 2021
     */
    int updateByPrimaryKey(Article record);

    /**
     * 批量插入
     * @author xzx
     * @date 2021/01/08 20:12
     * @param records
     * @return int
     */
    int insertList(@Param("list") List<Article> records);
}