package com.xzx.crawler.dao;

import com.xzx.crawler.entity.Article;
import com.xzx.crawler.entity.ArticleTest;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ArticleTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_copy1
     *
     * @mbg.generated Fri Jan 08 21:53:58 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_copy1
     *
     * @mbg.generated Fri Jan 08 21:53:58 CST 2021
     */
    int insert(ArticleTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_copy1
     *
     * @mbg.generated Fri Jan 08 21:53:58 CST 2021
     */
    int insertSelective(ArticleTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_copy1
     *
     * @mbg.generated Fri Jan 08 21:53:58 CST 2021
     */
    ArticleTest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_copy1
     *
     * @mbg.generated Fri Jan 08 21:53:58 CST 2021
     */
    int updateByPrimaryKeySelective(ArticleTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_copy1
     *
     * @mbg.generated Fri Jan 08 21:53:58 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(ArticleTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_copy1
     *
     * @mbg.generated Fri Jan 08 21:53:58 CST 2021
     */
    int updateByPrimaryKey(ArticleTest record);

    int insertList(@Param("list") List<Article> list);

    int deleteAll();
}